/* eslint-disable @typescript-eslint/no-explicit-any */
import { addMinutes, isBefore, parseISO } from "date-fns";

import { AppError } from "@/lib/http/errors";
import { enumerateSlots } from "@/lib/time";
import { createAdminSupabaseClient } from "@/lib/supabase/admin";
import { getShopSettings } from "@/lib/services/settings";
import type { AvailabilitySlotDto } from "@/types/domain";

function overlaps(aStart: Date, aEnd: Date, bStart: Date, bEnd: Date) {
  return aStart < bEnd && bStart < aEnd;
}

export async function getAvailabilityForDay(input: {
  barberId: string;
  serviceIds: string[];
  date: string;
}): Promise<AvailabilitySlotDto[]> {
  try {
    const supabase = createAdminSupabaseClient() as any;
    const settings = await getShopSettings();
    const days = ["sun", "mon", "tue", "wed", "thu", "fri", "sat"];
    const [y, m, d] = input.date.split("-").map(Number);
    const dayIndex = new Date(y, m - 1, d).getDay();
    const dayName = days[dayIndex];
    const dayConfig = (settings.weeklyHours as Record<string, { enabled: boolean; start: string; end: string }>)[dayName];

    console.log(`[getAvailabilityForDay] Date: ${input.date}, Day: ${dayName}, Config:`, dayConfig);

    if (!dayConfig?.enabled) {
      console.log(`[getAvailabilityForDay] Shop closed on ${dayName}`);
      return [];
    }

    const { data: services, error: servicesError } = await supabase
      .from("services")
      .select("id, duration_minutes")
      .in("id", input.serviceIds)
      .is("deleted_at", null)
      .eq("is_active", true);

    if (servicesError || !services || services.length !== input.serviceIds.length) {
      console.error(`[getAvailabilityForDay] Service error:`, servicesError);
      throw new AppError("SERVICES_NOT_FOUND", "Some services are unavailable.", 404, servicesError);
    }

    const serviceMinutes = (services as Array<{ duration_minutes: number }>).reduce(
      (sum, service) => sum + service.duration_minutes,
      0,
    );
    const slotMinutes =
      serviceMinutes +
      settings.defaultBufferBeforeMinutes +
      settings.defaultBufferAfterMinutes;

    console.log(`[getAvailabilityForDay] Service minutes: ${serviceMinutes}, Slot total: ${slotMinutes}`);

    const slots = enumerateSlots(
      input.date,
      dayConfig.start,
      dayConfig.end,
      settings.slotIntervalMinutes,
      slotMinutes,
      settings.timezone,
    );

    console.log(`[getAvailabilityForDay] Generated ${slots.length} slots.`);

    const windowStart = slots[0]?.startTime;
    const windowEnd = slots.at(-1)?.endTime;

    if (!windowStart || !windowEnd) {
      console.log(`[getAvailabilityForDay] No slots generated by enumerateSlots`);
      return [];
    }

    const [{ data: appointments, error: appointmentsError }, { data: overrides, error: overridesError }] =
      await Promise.all([
        supabase
          .from("appointments")
          .select(
            "id, start_time, end_time, buffer_before_minutes, buffer_after_minutes, delay_minutes, status",
          )
          .eq("barber_id", input.barberId)
          .is("deleted_at", null)
          .eq("status", "booked")
          .lte("start_time", windowEnd)
          .gte("end_time", windowStart),
        supabase
          .from("barber_availability_overrides")
          .select("id, start_time, end_time")
          .eq("barber_id", input.barberId)
          .is("deleted_at", null)
          .lte("start_time", windowEnd)
          .gte("end_time", windowStart),
      ]);

    if (appointmentsError) {
      console.error("[getAvailabilityForDay] Appointments fetch error:", appointmentsError);
      throw new AppError("AVAILABILITY_LOOKUP_FAILED", "Could not load appointments.", 500, appointmentsError);
    }

    // Gracefully handle missing overrides table (PGRST205)
    if (overridesError) {
      if ((overridesError as any).code === "PGRST205") {
        console.warn("[getAvailabilityForDay] Table 'barber_availability_overrides' missing. Skipping overrides.");
      } else {
        console.error("[getAvailabilityForDay] Overrides fetch error:", overridesError);
        throw new AppError("AVAILABILITY_LOOKUP_FAILED", "Could not load barber overrides.", 500, overridesError);
      }
    }

    const activeOverrides = overrides ?? [];

    return slots.map((slot) => {
      const slotStart = parseISO(slot.startTime);

      const appointmentConflict = ((appointments ?? []) as Array<{
        start_time: string;
        end_time: string;
        buffer_before_minutes: number;
        buffer_after_minutes: number;
        delay_minutes: number;
      }>).some((appointment) => {
        const blockedStart = addMinutes(
          parseISO(appointment.start_time),
          -appointment.buffer_before_minutes,
        );
        const blockedEnd = addMinutes(
          parseISO(appointment.end_time),
          appointment.buffer_after_minutes + appointment.delay_minutes,
        );

        return overlaps(slotStart, parseISO(slot.endTime), blockedStart, blockedEnd);
      });

      const overrideConflict = ((activeOverrides ?? []) as Array<{
        start_time: string;
        end_time: string;
      }>).some((override) =>
        overlaps(slotStart, parseISO(slot.endTime), parseISO(override.start_time), parseISO(override.end_time)),
      );

      return {
        startTime: slot.startTime,
        endTime: slot.endTime,
        available: !appointmentConflict && !overrideConflict && isBefore(new Date(), slotStart),
      };
    });
  } catch (err: any) {
    console.error("[getAvailabilityForDay] UNCAUGHT ERROR:", err);
    throw err;
  }
}
